### PR TITLE
feat(pages): improve airdrop list page

### PR DESCRIPTION
**Pull request by grikomsn**
## Description

This PR does quality of life improvements for the airdrop list page.

## Changes

List any technical changes.

- [x] [update airdrops list item contract address btn](https://github.com/CosmosContracts/juno-tools/pull/122/commits/0934b4c9c6c96cf55541af4c5b3fb132a872d683)
- [x] [make claim button invisible instead of hidden](https://github.com/CosmosContracts/juno-tools/pull/122/commits/167cd1b70a59fc2ea43bc7278d05a245bd18231e)
- [x] [set airdrops list table fixed height](https://github.com/CosmosContracts/juno-tools/pull/122/commits/62ada2170bbb1546c3873bd5479f2284c0979220)
- [x] [extract getAirdropDate utility](https://github.com/CosmosContracts/juno-tools/pull/122/commits/caf393288a3ae384b9131d81378bc013865ff2d2)
- [x] [improve airdrops table component typing](https://github.com/CosmosContracts/juno-tools/pull/122/commits/a81d77dadcb2d2c5569df8e2c78e01f8db6d2e2b)

## Screenshots

image

## Testing Steps

As a reviewer, what steps should I take to verify this is working correctly?

- open airdrops list page and make sure previous behaviors are the same

## Links

\-

### CODE REVIEW

**Review by findolor — COMMENTED** [review]
The airdrop list still short on a large screen. Height is 1340px. Can we do something to solve this?

Screen Shot 2022-03-30 at 10 30 18

**Comment by grikomsn** [comment]
@findolor, while I cannot reproduce it, I assume it's because the small number of entry that cause the table to not occupy the whole screen. Will rework the layout and push new changes soon.

**Comment by grikomsn** [comment]
@findolor fixed the table height and other improvements. This PR should be ready!

**Review by findolor — APPROVED** [review]
🚀

**Pull request merged**
