### PR TITLE
refactor(pages): remove interstitial airdrop pages

### PR DESCRIPTION
**Pull request by grikomsn**
## Description

This PR updates or removes interstitial airdrop pages.

## Changes

- [x] make `/airdrops` as `/airdrops/list`
- [x] make `/airdrops/manage` as `/airdrops/create`

Note: to ensure we're not throwing dead links, previous interstitial pages will show corresponding pages.

## Screenshots

\-

## Testing Steps

As a reviewer, what steps should I take to verify this is working correctly?

- make sure `/airdrops` is equal to `/airdrops/list`
- make sure `/airdrops/manage` is equal to `/aidrops/create`

## Links

\-

### CODE REVIEW

**Review by XanderJL — COMMENTED** [review]
Idk why the `list` and `create` files didn't show up in the diff 🤔

**Comment by grikomsn** [comment]
> Idk why the `list` and `create` files didn't show up in the diff 🤔

Because we're not changing any, only `/airdrops` and `/airdrops/manage` is touched.

**Comment by XanderJL** [comment]
> Because we're not changing any, only `/airdrops` and `/airdrops/manage` is touched.

Just so I understand correctly, the existing logic wasn't moved, it was deleted? And now `/airdrops` and `/airdrops/manage` are reusing the `/create` and `/lists` routes?

**Comment by grikomsn** [comment]
@XanderJL correct, reason being is so we don't have dead links.

**Comment by XanderJL** [comment]
@grikomsn Understood. Thanks for the context 😁

**Pull request merged**
