### PR TITLE
feat: update branding progress

### PR DESCRIPTION
**Pull request by RyanWarner**
Opening this PR for visibility, still work in progress. Will mark as ready for review until all related issues and PRs are resolved.

Related PRs:

- [x] https://github.com/deus-labs/junotools/pull/7
- [x] https://github.com/deus-labs/junotools/pull/8
- [x] https://github.com/deus-labs/junotools/pull/9
- [x] https://github.com/deus-labs/junotools/pull/10
- [x] https://github.com/deus-labs/junotools/pull/11
- [x] https://github.com/deus-labs/junotools/pull/12
- [x] https://github.com/deus-labs/junotools/pull/13
- [x] https://github.com/CosmosContracts/juno-tools/pull/6
- [x] https://github.com/CosmosContracts/juno-tools/pull/5
- [x] https://github.com/CosmosContracts/juno-tools/pull/7

### CODE REVIEW

**Comment by grikomsn** [comment]
Manually resolved conflicts in 6139d582935f9bbdc4a29c0f813da2415a457813. Waiting for @findolor's review before merging to `main` branch.

**Comment by findolor** [comment]
LGTM 🚀

**Review by findolor — APPROVED** [review]

**Comment by grikomsn** [comment]
Since `staging` was squash merged, retained `staging` git histories will be preserved in [`staging-2022-02-09`](https://github.com/CosmosContracts/juno-tools/tree/staging-2022-02-09) branch until further needed.

**Comment by findolor** [comment]
@grikomsn  Was that a mistake? I was always doing squash merge before and if it's a problem let me know :)

**Pull request merged**
